version: "3.8f"
services:
  db:
    image: "mongo"
    ports:
      - 27017:27017
    command: mongod --quiet --logpath=/dev/null

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: yarn start
    environment:
      - DB_URL=mongodb://db:27017/employees
      - PORT=3000
    depends_on:
      - db
