version: "3.8f"
services:

  db:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      -  data:/data/db
  api:
    build: ./
    ports:
      - 4300:4300
    environment:
      - DB_URL=mongodb://db:27017/employees
    depends_on:
      - db

volumes:
  data:
  logs: 



