version: "3.8f"
services:
  db:
    image: "mongo"
    ports:
      - 27017:27017
    logging:
      driver: none
  api:
    build: ./
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb://db:27017/employees
      - PORT=3000
    depends_on:
      - db
